version: '3.8'
services:
  main:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: main
    volumes:
      - .:/app
    tty: true
    command: /bin/bash -c " sleep infinity"
